### ISSUE TITLE
Trigger on hover

### ISSUE THREAD

**Issue by reinert** [GabiAxel/paper-fab-transitions#4]
How could I trigger transition on hover?

Can I customize how the transition is triggered?

**Comment by GabiAxel** [comment]
You can add mouseenter and mouseout listeners to the fab and invoke the speed dial / morph open() and close() respectively. If you want to disable the transition for the click event, you can add a mousedown listener to the fab and cancel the event.

**Comment by reinert** [comment]
Thanks!
